# Generated by Django 6.1 on 2026-08-13 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('INICIAR_SESION', 'Inicio de sesión'), ('CERRAR_SESION', 'Cierre de sesión'), ('CREAR', 'Creación'), ('EDITAR', 'Edición'), ('DESACTIVAR', 'Desactivación')], max_length=20, verbose_name='Acción')),
                ('modulo', models.CharField(max_length=50, verbose_name='Módulo')),
                ('registro', models.CharField(blank=True, max_length=50, verbose_name='Registro afectado')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
