# Generated by Django 6.1 on 2026-08-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('numero_identidad', models.CharField(max_length=20, unique=True, verbose_name='Número de identidad')),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('correo_electronico', models.EmailField(blank=True, max_length=150, verbose_name='Correo electrónico')),
                ('direccion', models.CharField(blank=True, max_length=250, verbose_name='Dirección')),
                ('estado_civil', models.CharField(blank=True, max_length=30, verbose_name='Estado civil')),
                ('contacto_emergencia', models.CharField(blank=True, max_length=150, verbose_name='Contacto de emergencia')),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de emergencia')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
    ]
