# Generated by Django 6.1 on 2026-08-12 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expedientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de consulta')),
                ('motivo_consulta', models.TextField(verbose_name='Motivo de consulta')),
                ('sintomas', models.TextField(blank=True, verbose_name='Síntomas')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico')),
                ('tratamiento', models.TextField(blank=True, verbose_name='Tratamiento')),
                ('indicaciones', models.TextField(blank=True, verbose_name='Indicaciones')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('proxima_cita', models.DateField(blank=True, null=True, verbose_name='Próxima cita')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='expedientes.expedienteclinico', verbose_name='Expediente clínico')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Consulta médica',
                'verbose_name_plural': 'Consultas médicas',
                'ordering': ['-fecha_consulta'],
            },
        ),
    ]
