# Generated by Django 6.1 on 2026-08-11 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpedienteClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedentes_personales', models.TextField(blank=True, verbose_name='Antecedentes personales')),
                ('antecedentes_familiares', models.TextField(blank=True, verbose_name='Antecedentes familiares')),
                ('antecedentes_quirurgicos', models.TextField(blank=True, verbose_name='Antecedentes quirúrgicos')),
                ('alergias', models.TextField(blank=True, verbose_name='Alergias')),
                ('fum', models.DateField(blank=True, null=True, verbose_name='Fecha de última menstruación')),
                ('vida_sexual_activa', models.BooleanField(blank=True, null=True, verbose_name='Vida sexual activa')),
                ('observaciones_generales', models.TextField(blank=True, verbose_name='Observaciones generales')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='expediente', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Expediente clínico',
                'verbose_name_plural': 'Expedientes clínicos',
            },
        ),
    ]
